pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  - master

pr:
  - 'azure-pipelines'

steps:
  - task: DotNetCoreInstaller@0
      inputs:
         version: '2.2.0'
  - script: 'dotnet restore ./DemoApp/DemoApp.sln'
  - script: 'dotnet build ./DemoApp/DemoApp.sln'
