pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  - master

pr:
  - 'azure-pipelines'

steps:
  - script: 'dotnet restore ./MovieNight/MovieNight.sln'
  - script: 'dotnet build ./MovieNight/MovieNight.sln'
